### ISSUE TITLE
TypeError: Cannot read property 'startActivityForResult' of undefined

### ISSUE THREAD

**Issue by liuy97** [iguissouma/nativescript-locate-address#2]
application.android.currentContext has been removed in nativescript 6.

**Comment by fpaaske** [comment]
https://github.com/iguissouma/nativescript-locate-address/blob/785b2b0a6bc7996cd217bd5156c00647ae451471/locate-address.android.ts#L51


Maybe do something like this?

```
(application.android.foregroundActivity || application.android.startActivity).startActivityForResult(intent, 0);
```

**Comment by fpaaske** [comment]
@iguissouma did you look into this?

**Comment by iguissouma** [comment]
Hello,
Sorry for not responding quickly, because I coudn't test it(my workspace with nativescript 6.0 is not operational).
I will try to publish a new version with the suggested fix.
I will ping you when it's pushed...
Sorry again.

**Comment by iguissouma** [comment]
@liuy97 @mrpaaske I've just published 1.0.3 with the fix.
could you please verify if it's working with Nativescript 6.0?

**Comment by liuy97** [comment]
@iguissouma , Thanks for your quick fix. It works fine with Nativescript 6 and nativescript-angular 8.2, tested in Android 8 and 9.

**Comment by fpaaske** [comment]
Thank you @iguissouma!
